#!/usr/bin/env bash
set -euo pipefail

IMAGE_SIZE="${1:?Usage: image.sh IMAGE_SIZE IMAGE}"
IMAGE="${2:?Usage: image.sh IMAGE_SIZE IMAGE}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
sudo CONTROLLER_IMAGE="${CONTROLLER_IMAGE}" ROLODEX_IMAGE="${ROLODEX_IMAGE}" UI_IMAGE="${UI_IMAGE}" LOCAL_DNS="${LOCAL_DNS:-}" TTYFORCE_DEV="${TTYFORCE_DEV:-}" TTYFORCE_LATEST="${TTYFORCE_LATEST:-}" IMAGE_HOSTNAME="${IMAGE_HOSTNAME:-}" "${SCRIPT_DIR}/install.sh" "${IMAGE_SIZE}" "${IMAGE}"
